import sublime
import sublime_plugin
import sys
import os
import json
import re

# ================== 关键步骤：加载第三方库 ==================
# 动态获取 User/Lib 的路径并加入环境变量
packages_path = sublime.packages_path()
lib_path = os.path.join(packages_path, 'User', 'Lib')

if lib_path not in sys.path:
    sys.path.append(lib_path)

# 现在可以导入 PyYAML 了
try:
    import yaml
except ImportError:
    print("Error: PyYAML not found. Please run pip install --target ...")
# ==========================================================

class YamlToJsCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        for region in self.view.sel():
            if not region.empty():
                text = self.view.substr(region)
                self.process_selection(edit, region, text)

    def process_selection(self, edit, region, yaml_text):
        try:
            # 1. 使用 PyYAML 解析 (安全加载)
            data = yaml.safe_load(yaml_text)
            
            # 2. 清洗数据 (去除 Emoji 和特殊符号)
            cleaned_data = self.clean_data(data)

            # 3. 转为 JS 对象字符串
            js_output = self.to_js_string(cleaned_data)
            
            # 4. 判断变量名 (如果是列表叫 proxies，如果是字典叫 config)
            var_name = "proxies" if isinstance(cleaned_data, list) else "config"
            
            result = f"\n\n// Generated by PyYAML Plugin\nconst {var_name} = {js_output};\n"
            
            # 5. 插入到编辑器
            self.view.insert(edit, region.end(), result)

        except Exception as e:
            sublime.status_message(f"YAML Convert Error: {str(e)}")
            print(f"YAML Error: {e}")

    def clean_text(self, text):
        """只保留中英文数字和常用符号"""
        if not isinstance(text, str):
            return text
        # 排除 Emoji 和乱码
        return re.sub(r'[^\u4e00-\u9fa5a-zA-Z0-9\s\.\-\_\|]', '', text).strip()

    def clean_data(self, data):
        """递归清洗数据结构"""
        if isinstance(data, dict):
            # 如果是字典，检查 name 字段，并递归处理所有值
            new_dict = {}
            for k, v in data.items():
                if k == 'name':
                    new_dict[k] = self.clean_text(v)
                else:
                    new_dict[k] = self.clean_data(v)
            return new_dict
        elif isinstance(data, list):
            return [self.clean_data(item) for item in data]
        else:
            return data

    def to_js_string(self, data):
        """将 Python 对象转为类似 JS 的源码 (键名无引号)"""
        json_str = json.dumps(data, ensure_ascii=False, indent=2)
        
        # 正则替换：去除键名的引号
        # 匹配 "key": 这种格式，但排除包含横杠或点的键名(JS里需要引号)
        def replacer(match):
            key = match.group(1)
            # 只有当 key 不包含特殊字符时才去引号
            if re.match(r'^[a-zA-Z0-9_]+$', key):
                return f"{key}:"
            return f"'{key}':" # 包含横杠等，改为单引号更像 JS

        return re.sub(r'"([a-zA-Z0-9_\-\.]+)"\s*:', replacer, json_str)