import sublime
import sublime_plugin
import json
import re
import yaml

class YamlToJsCommand(sublime_plugin.TextCommand):
    def run(self, edit):
        for region in self.view.sel():
            if not region.empty():
                text = self.view.substr(region)
                self.process_selection(edit, region, text)

    def process_selection(self, edit, region, yaml_text):
        try:
            # 1. 使用 PyYAML 解析
            data = yaml.safe_load(yaml_text)
            
            # 2. 全局清洗数据 (递归处理所有字符串值)
            cleaned_data = self.clean_data(data)

            # 3. 生成结果
            results = []
            
            # 判断数据结构：
            # 如果是字典 (例如 proxies: [...], other-config: {...})
            if isinstance(cleaned_data, dict):
                for key, value in cleaned_data.items():
                    # 将键名中的 - 转换为 _
                    var_name = key.replace('-', '_')
                    # 转换为 JS 对象字符串
                    js_val = self.to_js_string(value)
                    results.append(f"const {var_name} = {js_val};")
                
                final_output = "\n".join(results)
                
            # 如果是纯列表 (例如直接选中的 - {name:...})
            elif isinstance(cleaned_data, list):
                # 这种情况没有键名，我们可以给一个默认的，或者不做处理
                js_val = self.to_js_string(cleaned_data)
                final_output = f"const list_data = {js_val};"
            else:
                # 其他情况
                final_output = f"const data = {self.to_js_string(cleaned_data)};"

            # 4. 插入到编辑器
            result_text = f"\n\n// Generated by PyYAML Plugin\n{final_output}\n"
            self.view.insert(edit, region.end(), result_text)

        except Exception as e:
            sublime.status_message(f"YAML Convert Error: {str(e)}")
            print(f"YAML Error: {e}")

    def clean_text(self, text):
        """
        清洗文本：只保留中英文数字和常用符号 (. - _ | / @ :)
        注意：为了防止破坏 URL (如 https://...) 或路径 (/path/to)，
        我微调了正则，把 : / @ 也加入了允许列表。
        """
        if not isinstance(text, str):
            return text
        
        # [允许的字符范围]: 
        # \u4e00-\u9fa5 (中文)
        # a-zA-Z0-9 (英文数字)
        # \s (空格)
        # . - _ | (原有符号)
        # : / @ (新增：防止 URL 和路径被破坏)
        pattern = r'[^\u4e00-\u9fa5a-zA-Z0-9\s\.\-\_\|\:\/\@]'
        return re.sub(pattern, '', text).strip()

    def clean_data(self, data):
        """递归清洗所有数据结构中的字符串"""
        if isinstance(data, dict):
            # 递归处理字典的值
            return {k: self.clean_data(v) for k, v in data.items()}
        elif isinstance(data, list):
            # 递归处理列表的项
            return [self.clean_data(item) for item in data]
        elif isinstance(data, str):
            # 核心修改：如果是字符串，直接清洗
            return self.clean_text(data)
        else:
            # 其他类型 (bool, int, None) 保持原样
            return data

    def to_js_string(self, data):
        """将 Python 对象转为类似 JS 的源码 (键名无引号)"""
        json_str = json.dumps(data, ensure_ascii=False, indent=2)
        
        # 正则替换：去除键名的引号
        def replacer(match):
            key = match.group(1)
            # 只有当 key 不包含特殊字符时才去引号
            if re.match(r'^[a-zA-Z0-9_]+$', key):
                return f"{key}:"
            return f"'{key}':"

        return re.sub(r'"([a-zA-Z0-9_\-\.]+)"\s*:', replacer, json_str)